apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: llm-app
spec:
  template:
    spec:
      containers:
        - name: open-webui
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi